Repository enactjs/agate-apps, pull requests merged in 2018-10, with the labels that each got.

#55 CompactAppList
  console/src/components/CompactAppList/CompactAppList.js
  console/src/components/CompactAppList/package.json
  console/src/components/CompactHVAC/CompactHVAC.js
  console/src/components/CompactRadio/CompactRadio.js
  console/src/views/AppList.js
  console/src/views/Home.js
  console/src/views/Phone.less
Labels: enhancement

#50 Implement a rearrangeable UI
  console/src/App/App.js
  console/src/components/CompactAppList/CompactAppList.js
  console/src/components/CompactRadio/CompactRadio.js
  console/src/components/CustomLayout/CustomLayout.js
  console/src/components/CustomLayout/CustomLayout.less
  console/src/components/CustomLayout/package.json
  console/src/views/AppList.js
  console/src/views/HVAC.js
  console/src/views/HVAC.less
  console/src/views/Home.js
  console/src/views/Home.less
  console/src/views/Phone.js
  console/src/views/Radio.js
  console/src/views/Radio.less
Labels: enhancement

#75 Created a way to have and store private non-committed information
  console/.gitignore
  console/config.sample.js
  console/package.json
  console/src/App/AppContextProvider.js
  console/src/components/MapCore/MapCore.js
Labels: enhancement

#77 Feature: draggable context
  console/src/App/App.js
  console/src/App/AppContextProvider.js
  console/src/components/AppIconCell/AppIconCell.js
  console/src/components/CompactAppList/CompactAppList.js
  console/src/components/ContactThumbnail/ContactThumbnail.less
  console/src/components/CustomLayout/CustomLayout.js
  console/src/components/PresetItem/PresetItem.js
  console/src/views/HVAC.js
  console/src/views/Home.js
  console/src/views/Phone.js
  console/src/views/Phone.less
  console/src/views/Radio.js
  console/src/views/Radio.less
Labels: enhancement, exploration

#79 Console: Dashboard Screen
  console/src/App/App.js
  console/src/App/AppContextProvider.js
  console/src/components/Dashboard/svg/car.svg
  console/src/views/AppList.js
  console/src/views/Dashboard.js
  console/src/views/Dashboard.less
Labels: new component

#82 Updatable map
  console/src/components/CompactMap/CompactMap.js
  console/src/components/MapCore/MapCore.js
Labels: enhancement, exploration
